INSERT INTO symptom_rules (symptom, follow_up_questions) VALUES
('Chest Pain / Discomfort', '[
    "When did the pain start and what were you doing at that time?",
    "Can you describe the pain (pressure, squeezing, sharp, burning)?",
    "Does it radiate to your arm, jaw, or back?",
    "Is the pain constant or intermittent? How long does it last?",
    "Does rest or nitroglycerin relieve it?",
    "What is your current blood pressure and heart rate?",
    "Do you experience fluctuations in your heart rate or blood pressure during the pain?",
    "Do you have a history of angina, heart attack, or coronary artery disease?",
    "Have you undergone any heart surgeries or interventions (e.g., stent placement)?",
    "Do you have hypertension, diabetes, or high cholesterol?",
    "Any history of pericarditis or myocarditis?",
    "Do you smoke or use tobacco products? How much per day?",
    "What is your alcohol consumption like?",
    "Do you exercise regularly?",
    "Is the chest pain sudden and severe, described as a ''tearing'' sensation?",
    "Is it associated with profuse sweating, nausea, or sudden shortness of breath?",
    "Have you been under extreme stress or anxiety recently?",
    "Do you have a history of panic attacks?"
]'),
('Shortness of Breath (Dyspnea)', '[
    "Is the breathlessness at rest or with exertion?",
    "Do you have difficulty breathing when lying flat (orthopnea)?",
    "Do you wake up suddenly at night gasping for air (paroxysmal nocturnal dyspnea)?",
    "Is it getting progressively worse?",
    "What is your resting oxygen saturation (SpO2)?",
    "Have you noticed rapid or shallow breathing?",
    "Do you have a history of heart failure, asthma, or COPD?",
    "Have you had prior pulmonary embolism or lung diseases?",
    "Do you have prior MI, valve disease, or arrhythmias?",
    "Do you smoke or have occupational exposure to lung irritants?",
    "Physical activity level and diet?",
    "Is the shortness of breath sudden in onset and severe?",
    "Any chest pain, leg swelling, or sudden dizziness?",
    "Do you experience panic attacks or anxiety contributing to breathlessness?"
]'),
('Palpitations', '[
    "How long do the palpitations last (seconds, minutes, hours)?",
    "Is the rhythm regular or irregular?",
    "Are palpitations associated with activity, stress, or at rest?",
    "Do you feel lightheaded, chest pain, or shortness of breath during episodes?",
    "What is your current heart rate?",
    "Any prior episodes of bradycardia or tachycardia documented?",
    "Do you have thyroid disorders or known arrhythmias?",
    "Have you had prior cardiac ablations?",
    "Do you have electrolyte imbalances or adrenal disorders?",
    "High caffeine or energy drink intake?",
    "Tobacco or alcohol consumption?",
    "Have you lost consciousness during an episode?",
    "Is there associated chest pain, severe dizziness, or shortness of breath?",
    "Have you been stressed, anxious, or depressed recently?"
]'),
('Syncope (Fainting)', '[
    "What were you doing when you fainted (standing, sitting, exercising)?",
    "Was there any warning (dizziness, nausea, sweating)?",
    "How many episodes have occurred?",
    "Did anyone witness convulsive movements?",
    "What was your blood pressure and heart rate before/after the episode?",
    "History of heart disease, arrhythmias, or conduction disorders?",
    "Previous pacemaker or syncope evaluations?",
    "History of orthostatic hypotension or adrenal insufficiency?",
    "Dehydration, poor nutrition, or prolonged standing?",
    "Sudden, without warning, no identifiable triggers?",
    "Associated chest pain or palpitations?",
    "Recent panic attacks or anxiety episodes?"
]'),
('Peripheral Edema (Leg/Foot Swelling)', '[
    "Is the swelling bilateral or unilateral?",
    "When did it start and has it worsened?",
    "Is it worse at the end of the day or after standing?",
    "Any associated pain or redness?",
    "Blood pressure and heart rate readings?",
    "Recent weight gain?",
    "History of heart failure, kidney disease, liver disease, or DVT?",
    "Known chronic venous insufficiency or lymphedema?",
    "Prolonged standing/sitting or immobility?",
    "High salt intake or low protein diet?",
    "Sudden painful swelling, redness, or warmth (possible DVT)?",
    "Shortness of breath or chest pain (possible PE)?",
    "Stress, depression, or decreased physical activity recently?"
]'),
('Cough', '[
    "When did the cough start?",
    "Is it dry or productive (with phlegm)?",
    "Is the cough worse at night or during the day?",
    "Is it triggered by exertion or certain environments?",
    "Do you have a fever?",
    "What is your oxygen saturation (SpO2)?",
    "History of asthma, COPD, heart failure, or recent respiratory infection?",
    "Any history of tuberculosis or interstitial lung disease?",
    "Prior exposure to lung irritants or chronic lung conditions?",
    "Do you smoke or live in areas with poor air quality?",
    "Do you use cough suppressants or other medications?",
    "Is there blood in the sputum (hemoptysis)?",
    "Any unexplained weight loss or night sweats?",
    "Recent anxiety or emotional distress leading to cough?"
]'),
('Nocturia (Frequent Nighttime Urination)', '[
    "How many times do you urinate per night?",
    "Is the urine volume large or small?",
    "Do you wake up due to a strong urge or inability to hold urine?",
    "Has this recently worsened?",
    "Recent blood pressure and blood sugar readings?",
    "History of diabetes, heart failure, prostate issues, or urinary tract infections?",
    "History of kidney disease or bladder dysfunction?",
    "Fluid intake before bedtime (caffeine, alcohol)?",
    "Presence of blood in urine or painful urination?",
    "Rapid worsening of symptoms?",
    "Sleep disturbances due to anxiety or stress?"
]'),
('Dizziness or Lightheadedness', '[
    "Is the dizziness constant or episodic?",
    "Does it occur when standing up (orthostatic)?",
    "Any associated visual disturbances or hearing loss?",
    "Do you feel like you might faint?",
    "Blood pressure and heart rate lying down and standing (orthostatic measurements)?",
    "History of arrhythmias, hypotension, anemia, or inner ear problems?",
    "Previous syncopal episodes or stroke?",
    "Poor hydration or low salt intake?",
    "Sudden severe dizziness with chest pain or palpitations?",
    "Neurological deficits accompanying dizziness?",
    "Anxiety-related dizziness or hyperventilation episodes?"
]'),
('Diaphoresis (Excessive Sweating)', '[
    "Is sweating generalized or localized?",
    "Is it associated with exertion, rest, or specific triggers?",
    "Any associated chest pain, palpitations, or dizziness?",
    "Body temperature and heart rate readings?",
    "History of endocrine disorders (thyroid dysfunction, pheochromocytoma)?",
    "Past infections or autonomic dysfunction?",
    "Use of medications like beta-blockers or anticholinergics?",
    "Sudden unexplained heavy sweating without exertion?",
    "Sweating associated with chest pain or syncope?",
    "Anxiety, panic attacks, or depression contributing to sweating?"
]'),
('Cyanosis (Bluish Skin Discoloration)', '[
    "When did you first notice cyanosis?",
    "Is it localized or generalized?",
    "Does it worsen with exertion or improve at rest?",
    "Oxygen saturation (SpO2)?",
    "Heart rate and respiratory rate?",
    "History of congenital heart disease, chronic lung disease, or peripheral vascular disease?",
    "Prior episodes of low oxygenation or cyanosis?",
    "Exposure to cold environments or smoking habits?",
    "Sudden onset of cyanosis with breathlessness or chest pain?",
    "Limb or nail cyanosis vs. central cyanosis?",
    "Any psychological stress causing perception of cyanosis?"
]'),
('Rapid Breathing (Tachypnea)', '[
    "When did the rapid breathing start?",
    "Is it at rest or during exertion?",
    "Do you feel short of breath?",
    "Any associated chest pain, dizziness, or palpitations?",
    "Current respiratory rate, SpO2, and blood pressure?",
    "History of lung diseases, heart failure, or metabolic acidosis?",
    "Previous episodes of tachypnea, pulmonary embolism, or sepsis?",
    "Smoking or substance use (e.g., stimulants)?",
    "Sudden tachypnea with chest pain or hypoxia?",
    "Neurological deficits accompanying tachypnea?",
    "Anxiety or panic attack history?"
]'),
('Bradycardia (Slow Heart Rate)', '[
    "When did you first notice a slow heart rate?",
    "Do you experience dizziness, syncope, or fatigue?",
    "Is there a temporal relationship with medication intake?",
    "Current heart rate and blood pressure?",
    "Any documented episodes of bradycardia or pauses on ECG?",
    "History of heart block, sinus node dysfunction, or hypothyroidism?",
    "Prior pacemaker implantation or conduction abnormalities?",
    "Excessive endurance training or use of heart rate-lowering agents?",
    "Sudden bradycardia with syncope or severe hypotension?",
    "Progressive worsening of bradycardia?",
    "Any increased stress or depression?"
]'),
('Hypertension Symptoms', '[
    "Do you experience headaches, visual disturbances, or nosebleeds?",
    "Is the hypertension newly diagnosed or long-standing?",
    "Any recent changes in symptoms or medications?",
    "Recent blood pressure readings at rest and during activity?",
    "Any heart rate abnormalities?",
    "History of chronic hypertension, kidney disease, or cardiovascular events?",
    "Prior hypertensive crises or secondary hypertension diagnosis?",
    "High salt diet, sedentary lifestyle, obesity?",
    "Sudden very high blood pressure with chest pain, vision loss, or neurological deficits?",
    "Stress contributing to uncontrolled blood pressure?"
]'),
('Hypotension Symptoms', '[
    "Do you experience dizziness, lightheadedness, or fainting?",
    "Is it orthostatic (worse when standing)?",
    "Any recent weight loss or dehydration?",
    "Current blood pressure and heart rate?",
    "Orthostatic vital signs measurements?",
    "History of adrenal insufficiency, heart failure, or arrhythmias?",
    "Prior episodes of orthostatic hypotension or syncope?",
    "Poor fluid intake, excessive alcohol use, or prolonged standing?",
    "Sudden hypotension with confusion or pallor?",
    "Psychogenic causes of hypotension?"
]'),
('Heart Murmurs', '[
    "When was the murmur first detected?",
    "Do you experience chest pain, dyspnea, or fatigue?",
    "Any palpitations or syncope?",
    "Blood pressure, heart rate, and oxygen saturation?",
    "History of rheumatic fever, congenital heart disease, or endocarditis?",
    "Prior echocardiograms or heart valve surgery?",
    "Any history of drug use that affects the heart (e.g., stimulants)?",
    "Sudden onset of loud murmur with heart failure symptoms or syncope?",
    "Anxiety related to awareness of murmur?"
]'),
('Chest Heaviness', '[
    "When did the heaviness start?",
    "Is it associated with exertion, stress, or at rest?",
    "Does the heaviness radiate to other parts (arm, jaw, back)?",
    "What is your blood pressure and heart rate during the episode?",
    "Oxygen saturation (SpO2)?",
    "History of angina, heart attack, or GERD?",
    "Previous cardiac or gastrointestinal diagnoses?",
    "Smoking, high-fat diet, sedentary lifestyle?",
    "Sudden onset of severe heaviness with shortness of breath?",
    "Recent anxiety or panic episodes?"
]'),
('Nausea / Vomiting', '[
    "When did nausea start and is it continuous or intermittent?",
    "Any association with meals or certain activities?",
    "Is there vomiting of blood or bile?",
    "Current blood pressure, heart rate, and body temperature?",
    "History of heart attack, gastritis, or medication side effects?",
    "Previous gastrointestinal disorders or surgeries?",
    "Recent alcohol intake or use of nausea-inducing drugs?",
    "Severe vomiting with dehydration or altered mental status?",
    "Anxiety or psychological factors contributing to nausea?"
]'),
('Ankle Swelling', '[
    "Is the swelling unilateral or bilateral?",
    "When did it start and does it worsen over time?",
    "Is there associated pain, redness, or warmth?",
    "Blood pressure and heart rate?",
    "Weight changes over time?",
    "History of heart failure, kidney disease, liver disease, or DVT?",
    "Prior chronic venous insufficiency or lymphedema?",
    "Prolonged standing, high salt intake, immobility?",
    "Sudden painful unilateral swelling with redness (DVT)?",
    "Stress or depression leading to neglect of self-care?"
]'),
('Cold Extremities', '[
    "Is it continuous or episodic?",
    "Any associated color change (blue, pale)?",
    "Does it worsen in cold environments or with exertion?",
    "Peripheral pulse strength and temperature?",
    "Blood pressure and heart rate?",
    "History of peripheral arterial disease, Raynaud''s phenomenon, or heart failure?",
    "Any prior vascular surgeries or autonomic dysfunction?",
    "Smoking, exposure to cold environments, sedentary lifestyle?",
    "Sudden severe coldness and discoloration with pain (critical ischemia)?",
    "Anxiety or poor nutrition contributing to symptoms?"
]'),
('Pain in the Jaw, Neck, or Arm', '[
    "Is the pain constant or triggered by exertion or stress?",
    "Is the pain sharp, dull, or pressure-like?",
    "Does the pain radiate to other regions?",
    "Blood pressure and heart rate during episodes?",
    "Oxygen saturation?",
    "History of coronary artery disease, angina, or musculoskeletal disorders?",
    "Previous surgeries or injuries in the neck or jaw region?",
    "Smoking, poor posture, repetitive physical work?",
    "Sudden severe pain with diaphoresis, nausea, or dyspnea?",
    "Stress-related tension contributing to the pain?"
]'),
('Exercise Intolerance', '[
    "When did you start noticing reduced exercise capacity?",
    "Is it gradual or sudden onset?",
    "Do you experience fatigue, shortness of breath, or chest discomfort during exertion?",
    "Heart rate, blood pressure, and oxygen saturation before and after exertion?",
    "History of heart failure, chronic lung disease, or anemia?",
    "Prior cardiac surgeries or chronic illnesses?",
    "Sedentary lifestyle, smoking, obesity?",
    "Sudden inability to perform previously tolerable activities?",
    "Loss of motivation, depression, or anxiety limiting activity?"
]'),
('Difficulty Swallowing (Dysphagia)', '[
    "When did the difficulty start?",
    "Is it for solids, liquids, or both?",
    "Any associated pain or sensation of food getting stuck?",
    "Recent weight changes or signs of dehydration?",
    "History of GERD, stroke, or esophageal disorders?",
    "Previous surgeries or radiotherapy in the head/neck region?",
    "Smoking, alcohol use?",
    "Progressive worsening, significant weight loss, or hemoptysis?",
    "Stress or psychological factors contributing to dysphagia?"
]'),
('Heart Failure Symptoms', '[
    "Do you experience worsening shortness of breath, especially when lying flat (orthopnea)?",
    "Any swelling in legs, abdomen (ascites), or sudden weight gain?",
    "Do you experience fatigue or reduced exercise tolerance?",
    "Heart rate, blood pressure, oxygen saturation?",
    "Jugular venous pressure assessment?",
    "History of ischemic heart disease, cardiomyopathy, or valvular heart disease?",
    "Previous episodes of acute decompensated heart failure?",
    "High salt intake, low physical activity, alcohol use?",
    "Rapid worsening of edema, severe breathlessness at rest?",
    "Depression or poor adherence to therapy contributing to worsening symptoms?"
]'),
('Sudden Onset Weakness', '[
    "When did the weakness begin?",
    "Is it focal (one limb) or generalized?",
    "Any associated numbness, vision changes, or difficulty speaking?",
    "Blood pressure, heart rate, blood sugar levels?",
    "History of stroke, transient ischemic attacks (TIA), or seizures?",
    "Prior episodes of weakness or neurological deficits?",
    "Poor nutrition, sedentary lifestyle, substance abuse?",
    "Sudden weakness with facial drooping, speech difficulty, or visual loss (possible stroke)?",
    "Depression, stress, or somatic symptom disorders?"
]'),
('Restlessness / Anxiety', '[
    "When did restlessness or anxiety start?",
    "Is it constant or episodic?",
    "Any identifiable triggers (stressful events, medications)?",
    "Heart rate, blood pressure, respiratory rate?",
    "History of anxiety disorder, panic attacks, or psychiatric disorders?",
    "Prior psychological or medical evaluation for anxiety symptoms?",
    "Caffeine or stimulant use, irregular sleep patterns?",
    "Severe restlessness with palpitations, hyperventilation, or chest pain?",
    "Major life stressors or trauma history?"
]'),
('Cold Sweats', '[
    "When did the cold sweats start?",
    "Is it associated with chest pain, dizziness, or nausea?",
    "Does it occur at rest or during exertion?",
    "Body temperature, heart rate, blood pressure?",
    "History of myocardial infarction, hypoglycemia, or infections?",
    "Previous episodes of diaphoresis without clear cause?",
    "Substance use (stimulants, alcohol)?",
    "Sudden cold sweats with chest pain or severe hypotension?",
    "Anxiety or panic attack history contributing to symptoms?"
]'),
('Weight Gain', '[
    "When did the weight gain start?",
    "Is it gradual or sudden?",
    "Is it associated with swelling or shortness of breath?",
    "Body weight, blood pressure, heart rate?",
    "History of hypothyroidism, heart failure, or kidney disease?",
    "Prior episodes of rapid weight gain or fluid retention?",
    "Diet high in calories, low physical activity, or medication side effects?",
    "Rapid weight gain (>2 kg in a few days) with edema or breathlessness?",
    "Stress or depression contributing to overeating or inactivity?"
]'),
('Blood in Sputum (Hemoptysis)', '[
    "When did you first notice blood in your sputum?",
    "How much blood (small streaks, large amounts)?",
    "Any associated cough, fever, chest pain, or weight loss?",
    "Oxygen saturation, heart rate, and respiratory rate?",
    "History of tuberculosis, bronchitis, or lung cancer?",
    "Previous episodes of hemoptysis or lung disease history?",
    "Smoking, occupational exposures, recent travel?",
    "Large-volume hemoptysis, hypoxia, or massive bleeding?",
    "Anxiety related to fear of serious disease?"
]'),
('Low Urine Output (Oliguria)', '[
    "When did the low urine output start?",
    "Is it gradual or sudden?",
    "Is it associated with swelling, fatigue, or confusion?",
    "Blood pressure, heart rate, and hydration status?",
    "History of kidney disease, heart failure, or urinary tract obstruction?",
    "Prior episodes of oliguria or dialysis?",
    "Poor fluid intake, excessive diuretic use?",
    "Sudden severe drop in urine output with altered mental status or hypotension?",
    "Depression contributing to poor self-care or hydration?"
]'),
('Jaundice', '[
    "When did you first notice yellowing of skin or eyes?",
    "Is there associated abdominal pain, nausea, or dark urine?",
    "Any recent travel or exposure to hepatitis risk factors?",
    "Liver function tests, blood pressure, heart rate?",
    "History of liver disease, hepatitis, or gallbladder disease?",
    "Previous jaundice episodes or liver biopsies?",
    "Alcohol use, medication hepatotoxicity, high-risk sexual behavior?",
    "Sudden jaundice with confusion, bleeding tendencies (possible liver failure)?",
    "Stress contributing to neglect of health care?"
]'),
('Irregular Heartbeat (Arrhythmia)', '[
    "When did you first notice the irregular heartbeat?",
    "Is it constant or intermittent?",
    "Any associated dizziness, chest pain, or shortness of breath?",
    "Heart rate and rhythm on ECG?",
    "Any documented bradycardia or tachycardia episodes?",
    "History of arrhythmias, structural heart disease, or electrolyte imbalances?",
    "Previous pacemaker, ablation, or cardiac surgeries?",
    "Caffeine, alcohol use, or stimulant use?",
    "Sudden severe irregularity with chest pain, syncope, or heart failure symptoms?",
    "Anxiety or panic attacks contributing to palpitations?"
]'),
('Hoarseness of Voice', '[
    "When did the hoarseness begin?",
    "Is it persistent or intermittent?",
    "Any associated throat pain, difficulty swallowing, or cough?",
    "Temperature, oxygen saturation, heart rate?",
    "History of thyroid disorders, vocal cord paralysis, or laryngeal tumors?",
    "Prior surgeries or radiation therapy involving the neck?",
    "Smoking or alcohol use?",
    "Hoarseness lasting over 2 weeks or associated with weight loss, hemoptysis?",
    "Stress or vocal strain contributing to hoarseness?"
]'),
('Leg Pain on Exertion (Claudication)', '[
    "When did the leg pain start?",
    "Does it occur with walking or exertion and improve with rest?",
    "Is it localized or diffuse?",
    "Peripheral pulses and blood pressure measurements in legs?",
    "History of peripheral arterial disease, diabetes, or smoking?",
    "Previous vascular interventions or surgeries?",
    "Sedentary lifestyle, smoking, poor nutrition?",
    "Sudden onset of severe limb pain with pallor or numbness (critical limb ischemia)?",
    "Anxiety about mobility limitations or fear of disability?"
]'),
('Indigestion / Heartburn', '[
    "When did indigestion or heartburn start?",
    "Is it related to meals or lying down?",
    "Do you experience regurgitation, chest discomfort, or nausea?",
    "Temperature and blood pressure?",
    "History of GERD, peptic ulcer disease, or esophageal disorders?",
    "Previous upper GI endoscopy or H. pylori treatment?",
    "High-fat diet, smoking, alcohol use, or large meals before sleep?",
    "Unintended weight loss, dysphagia, or hematemesis?",
    "Stress contributing to GI symptoms?"
]'),
('Excessive Thirst (Polydipsia)', '[
    "When did the excessive thirst begin?",
    "How much fluid do you consume daily?",
    "Any associated frequent urination (polyuria)?",
    "Blood pressure, blood glucose level, and heart rate?",
    "History of diabetes mellitus, diabetes insipidus, or kidney disease?",
    "Prior episodes of polydipsia or electrolyte imbalances?",
    "High salt intake, diuretic use?",
    "Excessive thirst associated with confusion, polyuria, or sudden weight loss?",
    "Compulsive water drinking or anxiety-driven excessive thirst?"
]'),
('Dry Mouth (Xerostomia)', '[
    "When did the dry mouth begin?",
    "Is it constant or intermittent?",
    "Any difficulty speaking, swallowing, or taste changes?",
    "Oral mucosa appearance, hydration status?",
    "History of Sjogren''s syndrome, diabetes, or medication side effects?",
    "Previous episodes of dry mouth or head/neck radiotherapy?",
    "Use of anticholinergic drugs, alcohol, tobacco?",
    "Dry mouth associated with severe difficulty swallowing or weight loss?",
    "Stress or anxiety contributing to xerostomia?"
]'),
('Resting Tachycardia', '[
    "When did you first notice a consistently high resting heart rate?",
    "Do you experience palpitations, dizziness, or chest pain?",
    "Any relationship to caffeine, medications, or stress?",
    "Resting heart rate and blood pressure?",
    "ECG documentation of tachycardia type?",
    "History of hyperthyroidism, anemia, or arrhythmias?",
    "Prior episodes of tachycardia or autonomic dysfunction?",
    "High caffeine intake, stimulant use, poor sleep?",
    "Sudden tachycardia with chest pain, shortness of breath, or syncope?",
    "Anxiety or panic attacks contributing to elevated heart rate?"
]'),
('Sudden Chest Tightness', '[
    "When did the chest tightness begin?",
    "Is it related to exertion, rest, or stress?",
    "Does it radiate to arms, neck, or jaw?",
    "Blood pressure, heart rate, oxygen saturation?",
    "History of angina, GERD, asthma, or musculoskeletal conditions?",
    "Prior episodes of chest tightness or heart disease?",
    "Smoking, poor diet, sedentary lifestyle?",
    "Sudden severe tightness with sweating, nausea, and shortness of breath (possible MI)?",
    "Stress or panic contributing to chest tightness?"
]'),
('Difficulty Breathing Lying Down (Orthopnea)', '[
    "When did the orthopnea start?",
    "How many pillows do you use to sleep comfortably?",
    "Do you experience sudden breathlessness when lying flat?",
    "Heart rate, blood pressure, respiratory rate, and SpO2?",
    "History of heart failure, COPD, obesity, or sleep apnea?",
    "Prior episodes of orthopnea or pulmonary edema?",
    "Obesity, smoking, sedentary habits?",
    "Sudden worsening of orthopnea or associated pink frothy sputum?",
    "Anxiety contributing to perception of breathlessness?"
]'),
('Swelling in Abdomen (Ascites)', '[
    "When did the abdominal swelling begin?",
    "Is it progressive or sudden?",
    "Any associated abdominal pain, nausea, or shortness of breath?",
    "Abdominal girth measurements, blood pressure, and heart rate?",
    "History of liver disease, heart failure, or nephrotic syndrome?",
    "Prior episodes of ascites or abdominal surgeries?",
    "Alcohol use, viral hepatitis risk factors?",
    "Sudden severe abdominal distension or tenderness with confusion (possible spontaneous bacterial peritonitis)?",
    "Anxiety or depression limiting proper self-care or medical follow-up?"
]'),
('Severe Fatigue', '[
    "When did fatigue begin and is it constant or episodic?",
    "Is it exacerbated by physical activity or mental effort?",
    "Any associated weight loss, fever, or night sweats?",
    "Heart rate, blood pressure, oxygen saturation, and temperature?",
    "History of anemia, hypothyroidism, depression, or chronic infections?",
    "Prior episodes of unexplained fatigue or chronic disease diagnosis?",
    "Poor sleep, excessive caffeine or alcohol intake?",
    "Sudden extreme fatigue with shortness of breath or syncope?",
    "Stress, depression, or burnout?"
]'),
('Memory Loss or Confusion', '[
    "When did you first notice memory issues?",
    "Is it progressive or sudden?",
    "Any problems with attention, language, or problem-solving?",
    "Blood pressure, blood sugar, oxygen saturation?",
    "History of stroke, dementia, or neurological disease?",
    "Prior head injuries or transient ischemic attacks?",
    "Substance use, poor sleep, poor diet?",
    "Sudden confusion, disorientation, or personality changes?",
    "Depression, anxiety, or isolation?"
]'),
('Difficulty Concentrating', '[
    "When did you start having concentration problems?",
    "Is it constant or related to specific situations?",
    "Any associated fatigue, anxiety, or memory loss?",
    "Blood pressure, heart rate, and oxygen saturation?",
    "History of depression, ADHD, hypothyroidism, or anemia?",
    "Previous psychological or medical evaluations?",
    "Poor sleep, high caffeine intake, substance use?",
    "Sudden concentration loss with confusion or memory gaps?",
    "Stress, depression, or anxiety?"
]'),
('Mood Changes', '[
    "When did the mood changes start?",
    "Is it depression, irritability, anxiety, or mood swings?",
    "Any associated changes in sleep, appetite, or energy?",
    "Blood pressure, heart rate?",
    "History of depression, bipolar disorder, or psychiatric conditions?",
    "Previous mood disorder treatments or hospitalizations?",
    "Substance use, poor sleep hygiene, social isolation?",
    "Suicidal ideation or aggressive behavior?",
    "Recent stressors, bereavement, financial troubles?"
]'),
('Swollen Glands (Lymphadenopathy)', '[
    "When did you first notice the swelling?",
    "Is it painful or painless?",
    "Are the glands tender or fixed?",
    "Temperature, heart rate?",
    "History of infections (TB, HIV), cancer, or autoimmune diseases?",
    "Prior episodes of swollen glands or malignancies?",
    "Recent infections, tattoos, high-risk exposures?",
    "Rapidly enlarging or hard lymph nodes without pain?",
    "Stress, anxiety, or fear of serious disease?"
]'),
('Persistent Cough', '[
    "Duration of cough?",
    "Dry or productive?",
    "Any blood in sputum?",
    "Temperature, heart rate, oxygen saturation?",
    "History of asthma, COPD, GERD, or lung cancer?",
    "Previous episodes of chronic cough or TB?",
    "Smoking, occupational exposure?",
    "Unexplained weight loss, hemoptysis, or fever?",
    "Stress-related cough (habit cough)?"
]'),
('Visual Disturbances', '[
    "When did the visual disturbances start?",
    "Is it blurred vision, double vision, or sudden vision loss?",
    "Any association with headache, dizziness, or neurological symptoms?",
    "Blood pressure, heart rate?",
    "History of glaucoma, stroke, diabetes, or migraine?",
    "Previous ophthalmological evaluations?",
    "High screen time, poor lighting, or poor eye care habits?",
    "Sudden vision loss or visual field defects?",
    "Stress contributing to transient visual changes?"
]'),
('Difficulty Speaking (Dysarthria or Aphasia)', '[
    "When did the difficulty start?",
    "Is the speech slurred, slow, or completely lost?",
    "Any associated weakness, facial droop, or comprehension problems?",
    "Blood pressure, heart rate, oxygen saturation?",
    "History of stroke, neurodegenerative disorders, or head injury?",
    "Previous episodes of speech difficulty or neurological disease?",
    "Smoking, alcohol, drug use?",
    "Sudden onset of speech difficulty with weakness or altered consciousness?",
    "Anxiety contributing to transient speech problems?"
]'),
('Excessive Sweating at Night (Night Sweats)', '[
    "How frequent are the night sweats?",
    "Is it drenching or mild?",
    "Any associated fever, weight loss, or cough?",
    "Body temperature, heart rate?",
    "History of infections (TB, HIV), malignancies, or endocrine disorders?",
    "Previous episodes of night sweats or unexplained fever?",
    "Alcohol use, medications causing diaphoresis?",
    "Night sweats with weight loss, lymphadenopathy, or persistent cough?",
    "Stress or anxiety contributing to sweating?"
]'),
('Syncope (Fainting / Loss of Consciousness)', '[
    "When did the fainting episode occur?",
    "Was it sudden or preceded by warning signs (dizziness, palpitations, nausea)?",
    "How long did you lose consciousness?",
    "Was there any seizure-like activity or confusion after the episode?",
    "Blood pressure (lying, sitting, standing), heart rate, oxygen saturation during and after episode?",
    "History of heart disease, arrhythmias, neurological disorders, or prior syncope?",
    "Previous fainting episodes or head injuries?",
    "Dehydration, prolonged standing, medications (antihypertensives, diuretics), alcohol or drug use?",
    "Syncope with chest pain, palpitations, shortness of breath, or neurological deficits (possible cardiac or cerebrovascular emergency)?",
    "Stress, anxiety, or panic attack contributing to fainting?"
]');